# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_images', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
